### PR TITLE
Setting path for saving model and output images

### PR DESCRIPTION
**Pull request by Medha-B**

### CODE REVIEW

**Comment by Medha-B** [comment]
May I merge this pull request?

**Comment by Medha-B** [comment]
I have resolved the merge conflicts. Now may I merge this pull request?

**Comment by tokkuman** [comment]
It's a pull request to avoid conflict, right? If so, it's OK!

**Comment by Medha-B** [comment]
This pull request was made to create a folder with a .gitkeep for saving the model weights after training it. There were conflicts in this PR but they are resolved now. Also, there is no scope for any bugs, I think. I will merge this PR if it is an ok on your end.

**Comment by tokkuman** [comment]
I understood. It's OK!

**Comment by Medha-B** [comment]
Thanks a lot!

**Pull request merged**
